spring:
  kafka:
   template:
    default-topic: event    
   producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
   admin:
    properties:
     bootstrap.servers: localhost:9092
logging:
  level:
    root: INFO
    org.apache.kafka: DEBUG
   
   
